name: weight_tracker
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.14.0+5"
  firebase_database: "^3.0.7"
  redux: "^4.0.0"
  flutter_redux: "^0.6.0"
  tuple: "^1.0.3"
  intl: "^0.16.0"
  shared_preferences: "^0.5.3+4"
  mockito: "^4.1.1"
  google_sign_in: "^4.0.7"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/scale-bathroom.png
