name: weight_tracker
description: A new flutter project.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.20.1"
  firebase_database: "^6.0.0"
  redux: "^4.0.0+3"
  flutter_redux: "^0.7.0"
  tuple: "^1.0.3"
  intl: "^0.16.1"
  shared_preferences: "^0.5.12+4"
  google_sign_in: "^4.5.9"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^4.1.4"


flutter:

  uses-material-design: true
  assets:
    - assets/scale-bathroom.png
