name: weight_tracker
description: A new flutter project.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_auth: "^1.0.0"
  firebase_database: "^6.1.0"
  redux: "^4.0.0"
  flutter_redux: "^0.7.0"
  tuple: "^1.0.3"
  intl: "^0.17.0"
  shared_preferences: "2.0.1"
  google_sign_in: "^4.5.9"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^5.0.0"


flutter:

  uses-material-design: true
  assets:
    - assets/scale-bathroom.png
